# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\arang\PycharmProjects\ProjetInfo\GraphicGame\interface\game.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(9, 9, 521, 551))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.vuePlateau = QtWidgets.QGraphicsView(self.splitter)
        self.vuePlateau.setMouseTracking(True)
        self.vuePlateau.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vuePlateau.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vuePlateau.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vuePlateau.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.vuePlateau.setObjectName("vuePlateau")
        self.vueMain = QtWidgets.QGraphicsView(self.splitter)
        self.vueMain.setMouseTracking(True)
        self.vueMain.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vueMain.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vueMain.setObjectName("vueMain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonJoueur1 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonJoueur1.setObjectName("pushButtonJoueur1")
        self.verticalLayout.addWidget(self.pushButtonJoueur1)
        self.pushButtonJoueur2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonJoueur2.setObjectName("pushButtonJoueur2")
        self.verticalLayout.addWidget(self.pushButtonJoueur2)
        self.horizontalSliderZoom = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSliderZoom.setMinimum(100)
        self.horizontalSliderZoom.setMaximum(170)
        self.horizontalSliderZoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderZoom.setObjectName("horizontalSliderZoom")
        self.verticalLayout.addWidget(self.horizontalSliderZoom)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonTourner = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonTourner.setObjectName("pushButtonTourner")
        self.verticalLayout.addWidget(self.pushButtonTourner)
        self.pushButtonJouer = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonJouer.setObjectName("pushButtonJouer")
        self.verticalLayout.addWidget(self.pushButtonJouer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButtonNouvellePartie = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonNouvellePartie.setObjectName("pushButtonNouvellePartie")
        self.verticalLayout.addWidget(self.pushButtonNouvellePartie)
        self.pushButtonQuitter = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonQuitter.setObjectName("pushButtonQuitter")
        self.verticalLayout.addWidget(self.pushButtonQuitter)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        self.pushButtonQuitter.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fenêtre avec vues"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Boîte à outils"))
        self.pushButtonJoueur1.setText(_translate("MainWindow", "Joueur 1"))
        self.pushButtonJoueur2.setText(_translate("MainWindow", "Joueur 2"))
        self.pushButtonTourner.setText(_translate("MainWindow", "Tourner"))
        self.pushButtonJouer.setText(_translate("MainWindow", "Jouer"))
        self.pushButtonNouvellePartie.setText(_translate("MainWindow", "Nouvelle partie"))
        self.pushButtonQuitter.setText(_translate("MainWindow", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
