# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\arang\PycharmProjects\ProjetInfo\final\interface\welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomScreen(object):
    def setupUi(self, WelcomScreen):
        WelcomScreen.setObjectName("WelcomScreen")
        WelcomScreen.resize(1200, 800)
        WelcomScreen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(WelcomScreen)
        self.label.setGeometry(QtCore.QRect(560, 670, 241, 51))
        self.label.setStyleSheet("font: 12pt \"Onyx\";")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(WelcomScreen)
        self.widget.setGeometry(QtCore.QRect(290, 93, 711, 549))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(self.widget)
        self.icon.setStyleSheet("background-image: url(:/welcomIcon/welcomicon.jpg);")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/welcomIcon/welcomicon.jpg"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.bouton_jouer = QtWidgets.QPushButton(self.widget)
        self.bouton_jouer.setObjectName("bouton_jouer")
        self.horizontalLayout.addWidget(self.bouton_jouer)
        self.bouton_quitter = QtWidgets.QPushButton(self.widget)
        self.bouton_quitter.setObjectName("bouton_quitter")
        self.horizontalLayout.addWidget(self.bouton_quitter)

        self.retranslateUi(WelcomScreen)
        self.bouton_quitter.clicked.connect(WelcomScreen.close)
        QtCore.QMetaObject.connectSlotsByName(WelcomScreen)

    def retranslateUi(self, WelcomScreen):
        _translate = QtCore.QCoreApplication.translate
        WelcomScreen.setWindowTitle(_translate("WelcomScreen", "Dialog"))
        self.label.setText(_translate("WelcomScreen", "Paco & Antoine"))
        self.bouton_jouer.setText(_translate("WelcomScreen", "Jouer"))
        self.bouton_quitter.setText(_translate("WelcomScreen", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomScreen = QtWidgets.QDialog()
    ui = Ui_WelcomScreen()
    ui.setupUi(WelcomScreen)
    WelcomScreen.show()
    sys.exit(app.exec_())
